[project]
name = "ds-star"
version = "0.1.0"
description = "Implementation of Google's DS-Star paper"
authors = [
    {name = "jonathan-hsiao",email = "jhhsiao1@gmail.com"}
]
readme = "README.md"
requires-python = "^3.8"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "ds_star", from = "src"}]
